// iopll.v

// Generated using ACDS version 19.3 222

`timescale 1 ps / 1 ps
module iopll (
		input  wire       rst,        //      reset.reset
		output wire       locked,     //     locked.export
		input  wire       permit_cal, // permit_cal.export
		output wire [7:0] phout,      //      phout.phout
		output wire [1:0] extclk_out, // extclk_out.extclk_out
		output wire [1:0] lvds_clk,   //   lvds_clk.lvds_clk
		output wire [1:0] loaden,     //     loaden.loaden
		output wire       outclk_4,   //    outclk4.clk
		input  wire       adjpllin    //   adjpllin.clk
	);

	esram_altera_iopll_1930_rnqonzq iopll (
		.rst        (rst),        //   input,  width = 1,      reset.reset
		.locked     (locked),     //  output,  width = 1,     locked.export
		.permit_cal (permit_cal), //   input,  width = 1, permit_cal.export
		.phout      (phout),      //  output,  width = 8,      phout.phout
		.extclk_out (extclk_out), //  output,  width = 2, extclk_out.extclk_out
		.lvds_clk   (lvds_clk),   //  output,  width = 2,   lvds_clk.lvds_clk
		.loaden     (loaden),     //  output,  width = 2,     loaden.loaden
		.outclk_4   (outclk_4),   //  output,  width = 1,    outclk4.clk
		.adjpllin   (adjpllin)    //   input,  width = 1,   adjpllin.clk
	);

endmodule
