#!/bin/bash
set -x
module="intel_fpga_pcie_drv"
device="intel_fpga_pcie_drv"
mode="666"

# make sure uio module is loaded
sudo modprobe uio

# load the module
sudo /sbin/insmod ./$module.ko $* || exit 1

# Add device manually in case udev isn't set up to do so.
if [ ! -e /dev/$device ]; then
	major=`grep -w $device /proc/devices | cut -f1 -d" "`
	sudo mknod /dev/$device c $major 0
fi

# change permissions to allow all users to read/write
sudo chmod $mode /dev/$device
